server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sufi_cobranzas?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  jackson:
     serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
     time-zone: UTC
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
     